from __future__ import annotations

import enum


class ThesisStatus(str, enum.Enum):
    INTACT = "INTACT"
    STRENGTHENED = "STRENGTHENED"
    EVOLVED = "EVOLVED"
    WEAKENED = "WEAKENED"
    AT_RISK = "AT_RISK"
    INVALIDATED = "INVALIDATED"

    @property
    def is_terminal(self) -> bool:
        return self == ThesisStatus.INVALIDATED


class ProtectionMode(str, enum.Enum):
    MECHANICAL_ONLY = "MECHANICAL_ONLY"
    TIM_SUPERVISED = "TIM_SUPERVISED"
    DEGRADED_MECHANICAL = "DEGRADED_MECHANICAL"


class TIMMode(str, enum.Enum):
    OFF = "OFF"
    MEMORY_ONLY = "MEMORY_ONLY"
    SHADOW = "SHADOW"
    LIVE_PROTECTION = "LIVE_PROTECTION"
    LIVE_FULL = "LIVE_FULL"


class OriginQuality(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class TriggerType(str, enum.Enum):
    PRICE_MOVEMENT = "PRICE_MOVEMENT"
    MAE_MILESTONE = "MAE_MILESTONE"
    MF_MILESTONE = "MF_MILESTONE"
    TIME_ELAPSED = "TIME_ELAPSED"
    REGIME_CHANGE = "REGIME_CHANGE"
    PERIODIC = "PERIODIC"
    POSITION_CLOSING = "POSITION_CLOSING"
    POSITION_CLOSED = "POSITION_CLOSED"
    MANUAL = "MANUAL"


class JournalEventType(str, enum.Enum):
    ORIGIN_SET = "ORIGIN_SET"
    REVIEW_REQUESTED = "REVIEW_REQUESTED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    INTENT_PROPOSED = "INTENT_PROPOSED"
    INTENT_EXECUTED = "INTENT_EXECUTED"
    INTENT_FAILED = "INTENT_FAILED"
    INTENT_REJECTED = "INTENT_REJECTED"
    MEMORY_COMPRESSED = "MEMORY_COMPRESSED"
    THESIS_UPDATED = "THESIS_UPDATED"
    PROTECTION_MODE_CHANGED = "PROTECTION_MODE_CHANGED"
    DEGRADATION_TRIGGERED = "DEGRADATION_TRIGGERED"
    RECOVERY = "RECOVERY"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    WORKING_MEMORY_INITIALIZED = "WORKING_MEMORY_INITIALIZED"
    WORKING_MEMORY_REBUILT = "WORKING_MEMORY_REBUILT"
    WORKING_MEMORY_RESET = "WORKING_MEMORY_RESET"
    REASSOCIATED = "REASSOCIATED"
    ORIGIN_SYNTHETIC_RECONSTRUCTED = "ORIGIN_SYNTHETIC_RECONSTRUCTED"
    SCHEDULE_CREATED = "SCHEDULE_CREATED"
    MANUAL_INTERVENTION = "MANUAL_INTERVENTION"
    SYSTEM_CREATED = "SYSTEM_CREATED"


class IntentType(str, enum.Enum):
    HOLD = "HOLD"
    INCREASE_PROTECTION = "INCREASE_PROTECTION"
    DECREASE_PROTECTION = "DECREASE_PROTECTION"
    SCALE_OUT = "SCALE_OUT"
    EXIT = "EXIT"
    CANCEL_EXIT = "CANCEL_EXIT"
    ADJUST_TARGET = "ADJUST_TARGET"
    REQUEST_REVIEW = "REQUEST_REVIEW"
    ESCALATE = "ESCALATE"


class IntentStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    TIMEOUT = "TIMEOUT"


class ReviewTriggerType(str, enum.Enum):
    PRICE_THRESHOLD = "PRICE_THRESHOLD"
    TIME_ELAPSED = "TIME_ELAPSED"
    PERIODIC_INTERVAL = "PERIODIC_INTERVAL"
    REGIME_CHANGE = "REGIME_CHANGE"
    MANUAL = "MANUAL"
    SYSTEM_STARTUP = "SYSTEM_STARTUP"


class TradeMemoryRecoveryState(str, enum.Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
