import asyncio
import json
import os
import sys
import traceback

import aiohttp
import keyring
import questionary
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from ..llm.registry import LLMRegistry

console = Console()

LIVE_REST = "https://fapi.binance.com"
TESTNET_REST = "https://testnet.binancefuture.com"


def encrypt_keys(keys: dict, passphrase: str) -> bytes:
    salt = os.urandom(16)
    kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=salt, iterations=480000)
    key = Fernet.generate_key()
    f = Fernet(key)
    data = json.dumps(keys).encode()
    token = f.encrypt(data)
    payload = {"salt": salt.hex(), "key": key.decode(), "data": token.decode()}
    return json.dumps(payload).encode()


def decrypt_keys(encrypted: bytes, passphrase: str) -> dict:
    payload = json.loads(encrypted)
    salt = bytes.fromhex(payload["salt"])
    key = payload["key"].encode()
    f = Fernet(key)
    data = f.decrypt(payload["data"].encode())
    return json.loads(data)


async def fetch_top_symbols(base_url: str, limit: int = 50) -> list:
    url = f"{base_url}/fapi/v1/ticker/24hr"
    async with aiohttp.ClientSession() as session:
        async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
            if resp.status != 200:
                raise ConnectionError(f"Failed to fetch tickers: HTTP {resp.status}")
            data = await resp.json()
            sorted_data = sorted(data, key=lambda x: float(x.get("quoteVolume", 0) or 0), reverse=True)
            return [item["symbol"] for item in sorted_data[:limit]]


def parse_range_input(raw: str, max_val: int):
    result = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            parts = part.split("-", 1)
            try:
                start, end = int(parts[0].strip()), int(parts[1].strip())
            except (ValueError, TypeError):
                return None
            if start < 1 or end > max_val or start > end:
                return None
            result.extend(range(start, end + 1))
        else:
            try:
                val = int(part)
            except (ValueError, TypeError):
                return None
            if val < 1 or val > max_val:
                return None
            result.append(val)
    return sorted(set(result))


def write_config_toml(
    mode: str,
    anchors: list,
    alternates: list,
    llm_provider: str,
    custom_base_url: str,
    model_id: str,
    retention_days: int,
):
    lines = []
    lines.append("# APEX Configuration - Generated by Setup Wizard")
    lines.append("# Do NOT edit this file directly. Re-run the wizard to change settings.")
    lines.append("")
    lines.append("[binance]")
    lines.append(f'mode = "{mode}"')
    lines.append("")
    lines.append("[llm]")
    lines.append(f'provider = "{llm_provider}"')
    lines.append(f'model = "{model_id}"')
    if custom_base_url:
        lines.append(f'custom_base_url = "{custom_base_url}"')
    lines.append("")
    lines.append("[universe]")
    anchors_str = "[" + ", ".join(f'"{s}"' for s in anchors) + "]"
    alternates_str = "[" + ", ".join(f'"{s}"' for s in alternates) + "]"
    lines.append(f"anchors = {anchors_str}")
    lines.append(f"alternates = {alternates_str}")
    lines.append("")
    lines.append("[data]")
    lines.append(f"retention_days = {retention_days}")
    lines.append("")
    return "\n".join(lines) + "\n"


async def _select_symbols_interactive(prompt: str, choices: list, validate_fn) -> list:
    try:
        return await questionary.checkbox(
            prompt,
            choices=choices,
            validate=validate_fn,
        ).ask_async()
    except Exception as e:
        return None


async def _select_symbols_range(top_symbols: list, exclude: set, purpose: str) -> list:
    table = Table(title=f"{purpose} — Select by Number", title_style="bold cyan")
    table.add_column("#", style="dim")
    table.add_column("Symbol", style="cyan")
    available = [s for s in top_symbols if s not in exclude]
    for i, sym in enumerate(available, 1):
        table.add_row(str(i), sym)
    console.print(table)

    while True:
        raw = await questionary.text(
            f"Enter {purpose.lower()} by number (e.g. 1, 3, 5-10):"
        ).ask_async()
        if not raw and purpose == "Alternates":
            return []
        if not raw:
            console.print("[red]Enter at least one number.[/]")
            continue

        indices = parse_range_input(raw, len(available))
        if indices is None:
            console.print("[red]Invalid input. Use numbers and ranges like: 1, 3, 5-10[/]")
            continue
        if purpose == "Anchors" and len(indices) < 1:
            console.print("[red]Select at least one anchor coin.[/]")
            continue

        selected = [available[i - 1] for i in indices]
        confirm_table = Table(title="Your Selection", title_style="bold green")
        confirm_table.add_column("#", style="dim")
        confirm_table.add_column("Symbol", style="cyan")
        for j, sym in enumerate(selected, 1):
            confirm_table.add_row(str(j), sym)
        console.print(confirm_table)

        ok = await questionary.confirm("Confirm selection?").ask_async()
        if ok:
            return selected


async def run_setup_wizard():
    console.print(
        Panel.fit(
            Text.assemble(
                ("APEX", "bold cyan"),
                (" v0.1", "dim"),
                "\n\n",
                ("Terminal-First Crypto Trading Agent", "italic"),
                "\n",
                ("Phase 1: Setup & Ingestion Pipeline", "dim"),
            ),
            border_style="cyan",
            padding=(1, 4),
        )
    )

    mode = await questionary.select(
        "Choose environment:",
        choices=[
            questionary.Choice("Testnet (recommended for initial setup)", value="testnet"),
            questionary.Choice("Live (REAL funds - proceed with caution)", value="live"),
        ],
    ).ask_async()

    rest_url = TESTNET_REST if mode == "testnet" else LIVE_REST

    top_symbols = []
    try:
        with console.status("[yellow]Fetching top futures symbols by volume..."):
            top_symbols = await fetch_top_symbols(rest_url)
        console.print(f"[green]Loaded {len(top_symbols)} symbols from Binance Futures.[/]")
    except (aiohttp.ClientError, ConnectionError, asyncio.TimeoutError, OSError) as e:
        console.print(f"[yellow]Could not fetch symbols from Binance: {e}[/]")
        symbols_input = await questionary.text(
            "Enter symbols manually (comma-separated, e.g. BTCUSDT,ETHUSDT):"
        ).ask_async()
        if symbols_input:
            top_symbols = [s.strip().upper() for s in symbols_input.split(",") if s.strip()]
    except Exception as e:
        console.print(f"[bold red]Code bug in setup wizard: {type(e).__name__}: {e}[/]")
        traceback.print_exc()
        sys.exit(1)

    if not top_symbols:
        top_symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT"]
        console.print("[yellow]Using default symbol list.[/]")

    anchor_choices = [questionary.Choice(s, value=s) for s in top_symbols]
    anchors = await _select_symbols_interactive(
        "Select ANCHOR coins — Space to toggle, Enter to confirm:",
        anchor_choices,
        lambda vals: len(vals) >= 1 or "Select at least 1 anchor coin.",
    )
    if anchors is None:
        anchors = await _select_symbols_range(top_symbols, set(), "Anchors")

    alternate_choices = [
        questionary.Choice(s, value=s) for s in top_symbols if s not in anchors
    ]
    alternates = await _select_symbols_interactive(
        "Select ALTERNATE coins — Space to toggle, Enter to confirm:",
        alternate_choices,
        None,
    )
    if alternates is None:
        alternates = await _select_symbols_range(top_symbols, set(anchors), "Alternates")

    llm_provider = await questionary.select(
        "Select LLM Provider:",
        choices=[
            questionary.Choice("OpenCode Zen (free tier available)", value="opencode"),
            questionary.Choice("OpenAI", value="openai"),
            questionary.Choice("Anthropic", value="anthropic"),
            questionary.Choice("NVIDIA", value="nvidia"),
            questionary.Choice("Ollama (local)", value="ollama"),
            questionary.Choice("Custom OpenAI-compatible", value="custom"),
        ],
    ).ask_async()

    custom_base_url = ""
    if llm_provider == "custom":
        custom_base_url = await questionary.text("Enter custom OpenAI-compatible base URL:").ask_async()

    llm_key = await questionary.password("Enter LLM API Key:").ask_async()

    llm_registry = LLMRegistry(
        provider=llm_provider,
        api_key=llm_key,
        custom_base_url=custom_base_url,
    )

    model_id = None
    try:
        with console.status("[yellow]Fetching available models for your provider..."):
            models = await llm_registry.fetch_available_models()

        if not models:
            console.print("[yellow]Provider returned no models. You can enter one manually later.[/]")
        else:
            console.print(f"[green]Found {len(models)} models.[/]")
            model_choices = [questionary.Choice(m, value=m) for m in models[:100]]
            model_id = await questionary.select(
                "Select LLM Model to use:",
                choices=model_choices,
            ).ask_async()
            console.print(f"[dim]Selected model: {model_id}[/]")
    except Exception as e:
        console.print(f"[yellow]Could not fetch model list: {e}[/]")
        model_id = await questionary.text(
            "Enter model name manually (e.g. gpt-4o-mini, big-pickle):"
        ).ask_async()

    if model_id:
        console.print("[yellow]Testing LLM connection with selected model...[/]")
        try:
            llm_registry.model_id = model_id
            await llm_registry.verify_connection()
        except Exception as e:
            console.print(f"[yellow]LLM test failed with this model. You can change it later. Error: {e}[/]")

    console.print()
    console.print(Panel.fit(
        "[bold red]⚠️  CRITICAL: Ensure your Binance API key has 'Enable Futures'\n"
        "permissions checked in the Binance dashboard, or connection will fail![/]\n\n"
        "[dim]For testnet: Generate keys at https://testnet.binancefuture.com[/]",
        border_style="red",
    ))
    console.print()

    binance_key = await questionary.password("Enter Binance Futures API Key:").ask_async()
    binance_secret = await questionary.password("Enter Binance Futures API Secret:").ask_async()

    keyring_ok = False
    try:
        keyring.set_password("apex", "binance_key", binance_key)
        keyring.set_password("apex", "binance_secret", binance_secret)
        keyring.set_password("apex", "llm_key", llm_key)
        keyring_ok = True
        console.print("[green]API keys stored securely in OS keychain.[/]")
    except Exception as e:
        console.print(f"[yellow]OS keychain unavailable ({e}). Falling back to encrypted file...[/]")
        passphrase = await questionary.password(
            "Set an encryption passphrase for local key storage:",
            validate=lambda val: len(val) >= 8 or "Passphrase must be at least 8 characters.",
        ).ask_async()
        confirm = await questionary.password("Confirm encryption passphrase:").ask_async()
        if passphrase != confirm:
            console.print("[red]Passphrases do not match. Restarting setup.[/]")
            return await run_setup_wizard()

        keys = {"binance_key": binance_key, "binance_secret": binance_secret, "llm_key": llm_key}
        try:
            encrypted = encrypt_keys(keys, passphrase)
            with open("keys.enc", "wb") as f:
                f.write(encrypted)
            console.print("[green]API keys encrypted and saved to keys.enc[/]")
        except Exception as enc_err:
            console.print(f"[red]Failed to encrypt keys: {enc_err}[/]")
            sys.exit(1)

    config_content = write_config_toml(
        mode=mode,
        anchors=anchors,
        alternates=alternates,
        llm_provider=llm_provider,
        custom_base_url=custom_base_url,
        model_id=model_id or "",
        retention_days=90,
    )

    with open("config.toml", "w") as f:
        f.write(config_content)

    console.print()
    console.print(
        Panel.fit(
            Text.assemble(
                ("✅ Setup Complete!", "bold green"),
                "\n\n",
                ("Environment:    ", "dim"), (mode, "cyan"),
                "\n",
                ("Anchors:        ", "dim"), (f"{len(anchors)} coins", "cyan"),
                "\n",
                ("Alternates:     ", "dim"), (f"{len(alternates)} coins", "cyan"),
                "\n",
                ("LLM Provider:   ", "dim"), (llm_provider, "cyan"),
                "\n",
                ("LLM Model:      ", "dim"), (model_id or "auto", "cyan"),
                "\n",
                ("Key Storage:    ", "dim"), ("Keyring" if keyring_ok else "keys.enc (encrypted)", "cyan"),
            ),
            border_style="green",
            padding=(1, 2),
        )
    )
