import asyncio
import json
import os
import sys
import traceback

import aiohttp
import keyring
import questionary
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from ..llm.registry import LLMRegistry

console = Console()

LIVE_REST = "https://fapi.binance.com"
TESTNET_REST = "https://testnet.binancefuture.com"


def encrypt_keys(keys: dict, passphrase: str) -> bytes:
    salt = os.urandom(16)
    kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=salt, iterations=480000)
    key = Fernet.generate_key()
    f = Fernet(key)
    data = json.dumps(keys).encode()
    token = f.encrypt(data)
    payload = {"salt": salt.hex(), "key": key.decode(), "data": token.decode()}
    return json.dumps(payload).encode()


def decrypt_keys(encrypted: bytes, passphrase: str) -> dict:
    payload = json.loads(encrypted)
    salt = bytes.fromhex(payload["salt"])
    key = payload["key"].encode()
    f = Fernet(key)
    data = f.decrypt(payload["data"].encode())
    return json.loads(data)


async def fetch_top_symbols(base_url: str, limit: int = 50) -> list:
    url = f"{base_url}/fapi/v1/ticker/24hr"
    async with aiohttp.ClientSession() as session:
        async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
            if resp.status != 200:
                raise ConnectionError(f"Failed to fetch tickers: HTTP {resp.status}")
            data = await resp.json()
            sorted_data = sorted(data, key=lambda x: float(x.get("quoteVolume", 0) or 0), reverse=True)
            return [item["symbol"] for item in sorted_data[:limit]]


def write_config_toml(
    mode: str,
    anchors: list,
    alternates: list,
    llm_provider: str,
    custom_base_url: str,
    model_id: str,
    retention_days: int,
    max_timeframe_m: int = 1440,
    correlation_cfg: dict | None = None,
    execution_mode: str = "testnet",
    leverage: int = 10,
    sizing_mode: str = "risk_pct",
    sizing_value: float = 2.0,
):
    lines = []
    lines.append("# APEX Configuration - Generated by Setup Wizard")
    lines.append("# Do NOT edit this file directly. Re-run the wizard to change settings.")
    lines.append("")
    lines.append("[binance]")
    lines.append(f'mode = "{mode}"')
    lines.append("")
    lines.append("[llm]")
    lines.append(f'provider = "{llm_provider}"')
    lines.append(f'model = "{model_id}"')
    if custom_base_url:
        lines.append(f'custom_base_url = "{custom_base_url}"')
    lines.append("")
    lines.append("[universe]")
    anchors_str = "[" + ", ".join(f'"{s}"' for s in anchors) + "]"
    alternates_str = "[" + ", ".join(f'"{s}"' for s in alternates) + "]"
    lines.append(f"anchors = {anchors_str}")
    lines.append(f"alternates = {alternates_str}")
    lines.append("")
    lines.append("[data]")
    lines.append(f"retention_days = {retention_days}")
    lines.append(f"max_timeframe_m = {max_timeframe_m}")
    lines.append("")
    lines.append("[execution]")
    lines.append(f'mode = "{execution_mode}"')
    lines.append(f"leverage = {leverage}")
    lines.append(f'sizing_mode = "{sizing_mode}"')
    lines.append(f"sizing_value = {sizing_value}")
    lines.append("")

    if correlation_cfg:
        lines.append("[correlation]")
        for key, val in correlation_cfg.items():
            if isinstance(val, bool):
                lines.append(f"{key} = {'true' if val else 'false'}")
            elif isinstance(val, str):
                lines.append(f'{key} = "{val}"')
            else:
                lines.append(f"{key} = {val}")
        lines.append("")
    return "\n".join(lines) + "\n"


async def run_setup_wizard():
    try:
        await _setup_impl()
    except (KeyboardInterrupt, EOFError):
        console.print()
        try:
            quit_now = await questionary.confirm(
                "Interrupted. Quit setup?", default=True
            ).ask_async()
        except (KeyboardInterrupt, EOFError):
            quit_now = True
        if quit_now:
            console.print("[yellow]Setup cancelled.[/]")
            sys.exit(0)
        console.print("[green]Restarting setup...[/]")
        return await run_setup_wizard()


async def _setup_impl():
    console.print(
        Panel.fit(
            Text.assemble(
                ("APEX", "bold cyan"),
                (" v0.1", "dim"),
                "\n\n",
                ("Terminal-First Crypto Trading Agent", "italic"),
                "\n",
                ("Phase 1: Setup & Ingestion Pipeline", "dim"),
            ),
            border_style="cyan",
            padding=(1, 4),
        )
    )

    mode = await questionary.select(
        "Choose environment:",
        choices=[
            questionary.Choice("Testnet (recommended for initial setup)", value="testnet"),
            questionary.Choice("Live (REAL funds - proceed with caution)", value="live"),
        ],
    ).ask_async()

    execution_mode = await questionary.select(
        "Execution mode:",
        choices=[
            questionary.Choice("Testnet (Recommended)", value="testnet"),
            questionary.Choice("Live (REAL funds)", value="live"),
        ],
        default="testnet",
    ).ask_async()

    leverage = int(
        await questionary.text(
            "Leverage for all trades (default: 10):",
            default="10",
        ).ask_async()
    )

    sizing_mode = await questionary.select(
        "Position sizing mode:",
        choices=[
            questionary.Choice("Risk Percentage (e.g., 2% of equity)", value="risk_pct"),
            questionary.Choice("Fixed USDT Amount (e.g., $100 per trade)", value="fixed_usdt"),
        ],
        default="risk_pct",
    ).ask_async()

    sizing_prompt = "Enter risk percentage (e.g., 2.0 for 2%):" if sizing_mode == "risk_pct" else "Enter fixed USDT amount (e.g., 100.0):"
    sizing_value = float(
        await questionary.text(sizing_prompt, default="2.0").ask_async()
    )

    rest_url = TESTNET_REST if mode == "testnet" else LIVE_REST

    top_symbols = []
    try:
        with console.status("[yellow]Fetching top futures symbols by volume..."):
            top_symbols = await fetch_top_symbols(rest_url)
        console.print(f"[green]Loaded {len(top_symbols)} symbols from Binance Futures.[/]")
    except (aiohttp.ClientError, ConnectionError, asyncio.TimeoutError, OSError) as e:
        console.print(f"[yellow]Could not fetch symbols from Binance: {e}[/]")
        symbols_input = await questionary.text(
            "Enter symbols manually (comma-separated, e.g. BTCUSDT,ETHUSDT):"
        ).ask_async()
        if symbols_input:
            top_symbols = [s.strip().upper() for s in symbols_input.split(",") if s.strip()]
    except Exception as e:
        console.print(f"[bold red]Code bug in setup wizard: {type(e).__name__}: {e}[/]")
        traceback.print_exc()
        sys.exit(1)

    if not top_symbols:
        top_symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT"]
        console.print("[yellow]Using default symbol list.[/]")

    anchor_choices = [questionary.Choice(s, value=s) for s in top_symbols]
    anchors = await questionary.checkbox(
        "Select ANCHOR coins (core observation targets) — Space to toggle, Enter to confirm:",
        choices=anchor_choices,
        validate=lambda vals: len(vals) >= 1 or "Select at least 1 anchor coin.",
    ).ask_async()

    alternate_choices = [
        questionary.Choice(s, value=s) for s in top_symbols if s not in anchors
    ]
    alternates = await questionary.checkbox(
        "Select ALTERNATE coins (lagged reaction targets) — Space to toggle, Enter to confirm:",
        choices=alternate_choices,
    ).ask_async()

    llm_provider = ""
    custom_base_url = ""
    llm_key = ""
    model_id = ""

    needs_provider = True
    while True:
        if needs_provider:
            llm_provider = await questionary.select(
                "Select LLM Provider:",
                choices=[
                    questionary.Choice("OpenCode Zen (free tier available)", value="opencode"),
                    questionary.Choice("OpenAI", value="openai"),
                    questionary.Choice("Anthropic", value="anthropic"),
                    questionary.Choice("NVIDIA", value="nvidia"),
                    questionary.Choice("Ollama (local)", value="ollama"),
                    questionary.Choice("Custom OpenAI-compatible", value="custom"),
                ],
            ).ask_async()

            custom_base_url = ""
            if llm_provider == "custom":
                custom_base_url = await questionary.text("Enter custom OpenAI-compatible base URL:").ask_async()

            llm_key = await questionary.password("Enter LLM API Key:").ask_async()

            llm_registry = LLMRegistry(
                provider=llm_provider,
                api_key=llm_key,
                custom_base_url=custom_base_url,
            )

            model_id = ""
            needs_model = True
        else:
            needs_model = True

        if needs_model:
            model_id = ""
            fetch_error = False
            try:
                with console.status("[yellow]Fetching available models..."):
                    models = await llm_registry.fetch_available_models()
            except Exception as e:
                console.print(f"[yellow]Could not fetch model list: {e}[/]")
                fetch_error = True

            if fetch_error:
                model_id = await questionary.text(
                    "Enter model name manually (e.g. gpt-4o-mini, big-pickle):"
                ).ask_async()
            elif not models:
                console.print("[yellow]Provider returned no models.[/]")
                model_id = await questionary.text(
                    "Enter model name manually:"
                ).ask_async()
            else:
                console.print(f"[green]Found {len(models)} models.[/]")
                model_choices = [questionary.Choice(m, value=m) for m in models[:100]]
                model_id = await questionary.select(
                    "Select LLM Model to use:",
                    choices=model_choices,
                ).ask_async()

        if not model_id:
            console.print("[red]No model selected. Please try again or skip.[/]")
            action = await questionary.select(
                "What would you like to do?",
                choices=[
                    "[RETRY] Try again with different provider/key",
                    "[SKIP] Skip LLM setup for now",
                    "[ABORT] Abort setup",
                ],
            ).ask_async()
            if action == "[RETRY] Try again with different provider/key":
                needs_provider = True
                continue
            elif action == "[SKIP] Skip LLM setup for now":
                llm_provider = ""
                model_id = ""
                break
            else:
                console.print("[red]Setup aborted.[/]")
                sys.exit(1)

        console.print(f"[cyan]Testing connection with model: {model_id}...[/]")
        llm_registry.model_id = model_id
        test_ok = True
        try:
            await llm_registry.verify_connection()
            console.print("[green][OK] LLM connection successful![/]")
        except Exception as e:
            console.print(f"[bold red][FAIL] LLM test failed: {e}[/]")
            test_ok = False

        if test_ok:
            break

        action = await questionary.select(
            "What would you like to do?",
            choices=[
                "[RETRY] Choose a different model",
                "[RETRY] Change provider or API key",
                "[SKIP] Skip LLM setup for now",
                "[ABORT] Abort setup",
            ],
        ).ask_async()

        if action == "[RETRY] Choose a different model":
            needs_provider = False
            continue
        elif action == "[RETRY] Change provider or API key":
            needs_provider = True
            continue
        elif action == "[SKIP] Skip LLM setup for now":
            console.print("[yellow]Skipping LLM setup. Re-run wizard to configure later.[/]")
            llm_provider = ""
            model_id = ""
            break
        else:
            console.print("[red]Setup aborted.[/]")
            sys.exit(1)

    console.print()
    console.print(Panel.fit(
        "[bold red][WARN] CRITICAL: Ensure your Binance API key has 'Enable Futures'\n"
        "permissions checked in the Binance dashboard, or connection will fail![/]\n\n"
        "[dim]For testnet: Generate keys at https://testnet.binancefuture.com[/]",
        border_style="red",
    ))
    console.print()

    binance_key = await questionary.password("Enter Binance Futures API Key:").ask_async()
    binance_secret = await questionary.password("Enter Binance Futures API Secret:").ask_async()

    keyring_ok = False
    keys_payload = {"binance_key": binance_key, "binance_secret": binance_secret}
    if llm_key:
        keys_payload["llm_key"] = llm_key

    try:
        keyring.set_password("apex", "binance_key", binance_key)
        keyring.set_password("apex", "binance_secret", binance_secret)
        if llm_key:
            keyring.set_password("apex", "llm_key", llm_key)
        keyring_ok = True
        console.print("[green]API keys stored securely in OS keychain.[/]")
    except Exception as e:
        console.print(f"[yellow]OS keychain unavailable ({e}). Falling back to encrypted file...[/]")
        passphrase = await questionary.password(
            "Set an encryption passphrase for local key storage:",
            validate=lambda val: len(val) >= 8 or "Passphrase must be at least 8 characters.",
        ).ask_async()
        confirm = await questionary.password("Confirm encryption passphrase:").ask_async()
        if passphrase != confirm:
            console.print("[red]Passphrases do not match. Restarting setup.[/]")
            return await run_setup_wizard()

        try:
            encrypted = encrypt_keys(keys_payload, passphrase)
            with open("keys.enc", "wb") as f:
                f.write(encrypted)
            console.print("[green]API keys encrypted and saved to keys.enc[/]")
        except Exception as enc_err:
            console.print(f"[red]Failed to encrypt keys: {enc_err}[/]")
            sys.exit(1)

    corr_defaults = {
        "rolling_window_candles": 500,
        "max_lag": 15,
        "base_half_life": 60,
        "min_half_life": 15,
        "max_half_life": 180,
        "acf_truncation_lag": 10,
        "alpha_crit": 0.01,
        "update_buffer_candles": 10,
    }

    console.print("\n[bold cyan]Correlation Engine Configuration[/]")
    console.print(
        "Default parameters for the Lagged Exponentially-Weighted "
        "Cross-Correlation (LEW-CCF) engine:"
    )
    corr_table = Table(title="LEW-CCF Defaults")
    corr_table.add_column("Parameter", style="bold")
    corr_table.add_column("Default", style="cyan")
    for key, val in corr_defaults.items():
        corr_table.add_row(key, str(val))
    console.print(corr_table)

    accept_corr = await questionary.confirm(
        "Accept correlation defaults?", default=True
    ).ask_async()

    if not accept_corr:
        console.print("[yellow]Enter custom correlation parameters:[/]")
        for key in corr_defaults:
            raw = await questionary.text(
                f"{key}:",
                default=str(corr_defaults[key]),
            ).ask_async()
            if raw.strip():
                orig = corr_defaults[key]
                if isinstance(orig, float):
                    corr_defaults[key] = float(raw)
                else:
                    corr_defaults[key] = int(raw)

    max_timeframe_m = int(
        await questionary.text(
            "Enter the maximum minute timeframe to aggregate continuously "
            "(e.g., 60 for 1m-60m, 1440 for 1 day). [Default: 1440]:",
            default="1440",
        ).ask_async()
    )

    config_content = write_config_toml(
        mode=mode,
        anchors=anchors,
        alternates=alternates,
        llm_provider=llm_provider,
        custom_base_url=custom_base_url,
        model_id=model_id or "",
        retention_days=90,
        max_timeframe_m=max_timeframe_m,
        correlation_cfg=corr_defaults,
        execution_mode=execution_mode,
        leverage=leverage,
        sizing_mode=sizing_mode,
        sizing_value=sizing_value,
    )

    with open("config.toml", "w") as f:
        f.write(config_content)

    console.print()
    console.print(
        Panel.fit(
            Text.assemble(
                ("[OK] Setup Complete!", "bold green"),
                "\n\n",
                ("Environment:    ", "dim"), (mode, "cyan"),
                "\n",
                ("Execution Mode: ", "dim"), (execution_mode, "cyan"),
                "\n",
                ("Leverage:       ", "dim"), (f"{leverage}x", "cyan"),
                "\n",
                ("Sizing:         ", "dim"), (f"{sizing_value} {'% of equity' if sizing_mode == 'risk_pct' else 'USDT fixed'}", "cyan"),
                "\n",
                ("Anchors:        ", "dim"), (f"{len(anchors)} coins", "cyan"),
                "\n",
                ("Alternates:     ", "dim"), (f"{len(alternates)} coins", "cyan"),
                "\n",
                ("Max Timeframe:  ", "dim"), (f"Continuous 1m–{max_timeframe_m}m", "cyan"),
                "\n",
                ("LLM Provider:   ", "dim"), (llm_provider, "cyan"),
                "\n",
                ("LLM Model:      ", "dim"), (model_id or "auto", "cyan"),
                "\n",
                ("Key Storage:    ", "dim"), ("Keyring" if keyring_ok else "keys.enc (encrypted)", "cyan"),
            ),
            border_style="green",
            padding=(1, 2),
        )
    )
